### ISSUE TITLE
Match with url hash seems not work as expected

### ISSUE THREAD

**Issue by yunsii** [lionel-rowe/browser-extension-url-match#3]
Pattern: `https://test.com/index.html#/*`

Test: `https://test.com/index.html#/server`

Current result is `false`, but it should be `true` instead?

**Comment by lionel-rowe** [comment]
Returning `false` in that case is definitely wrong, but possibly the matcher should simply be invalid. Neither [Chrome](https://developer.chrome.com/docs/extensions/mv3/match_patterns/) nor [MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/Match_patterns) docs mention hash content as being valid in a match pattern. I'm curious, what happens if you specify such a URL in your extension's manifest? Does it fail to match? Or simply ignore the hash and match the base URL? Or only matches if the hash happens to have that value on page load?

Note that this library is specifically intended to support browser extension match patterns. If your use case doesn't involve browser extensions, you're most likely better off using the native [`URLPattern`](https://developer.mozilla.org/en-US/docs/Web/API/URLPattern) API (or a polyfill where necessary).

**Comment by yunsii** [comment]
I write a Tampermonkey userscript with this [match pattern](https://www.tampermonkey.net/documentation.php?locale=en#meta:match) for our specific platforms. I want to use this library to load differrent userscript with specific match pattern.

It is not work as my expected becase of the missing match.

**Comment by lionel-rowe** [comment]
> I write a Tampermonkey userscript with this [match pattern](https://www.tampermonkey.net/documentation.php?locale=en#meta:match) for our specific platforms. I want to use this library to load differrent userscript with specific match pattern.
> 
> It is not work as my expected becase of the missing match.

Tampermonkey uses its own implementation internally, it doesn't rely on this library. From testing, Tampermonkey fails to match anything if `@match` contains a hash, and matches all hashes if it doesn't:

```js
// ==UserScript==
// @name         Hash URL test
// @version      0.1
// @description  ...
// @match        https://example.com/#foo
// @match        https://example.com#bar
// ==/UserScript==

alert(1)
```

The script above does nothing when visiting https://example.com/#foo or https://example.com#bar.

Conversely, the script below:

```js
// ==UserScript==
// @name         Hash URL test 2
// @version      0.1
// @description  ...
// @match        https://example.com/
// ==/UserScript==

alert(1)
```

runs on both https://example.com/#foo and https://example.com#bar, because the hash in the URL is simply ignored.

You can implement hash routing internally within a userscript something like this, though:

```js
// ==UserScript==
// @name         Hash router
// @version      0.1
// @description  A simple hash router example
// @match        https://example.com/
// ==/UserScript==

function run() {
    const route = new URL(location.href).hash.slice(1)
    switch (route) {
        case '/foo': {
            return alert('foo route!')
        }
        case '/bar': {
            return alert('bar route!')
        }
        default: {
            if (route.startsWith('/')) {
                return alert('sorry, route not found!')
            }
            return alert('sorry, bad request!')
        }
    }
}

run()

window.addEventListener('hashchange', run)
```

**Comment by lionel-rowe** [comment]
Chrome extension Manifest V3:

* `https://example.com#` is invalid as it's missing a slash after the origin (fails to load extension)
* `https://example.com/#` is "valid" but matches nothing (neither `https://example.com/` nor `https://example.com/#` nor `https://example.com/%23`)
* Same as above for contentful hashes like `#foo`

This library aims to be stricter than actual implementations in cases where patterns are "valid" but fail to match any URLs, so v1.2.0 treats any pattern containing a hash as invalid.
